[package]
name = "rminecraft"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glm = "0.2.3"
glutin = "0.31.2"
serde = { version = "1.0.196", features = ["derive"] }
shipyard = "0.6.2"
